version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
    groups:
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
      dependencies:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
    ignore:
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react-test-renderer'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/packages/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'backend'
    commit-message:
      prefix: 'chore(backend)'
      prefix-development: 'chore(backend)'
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
          - 'nest-*'
      testing:
        dependency-type: 'development'
        patterns:
          - 'jest*'
          - '@types/jest'
          - 'supertest'
          - '@types/supertest'
      backend-dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
      backend-dependencies:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/apps/admin'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'admin'
    commit-message:
      prefix: 'chore(admin)'
      prefix-development: 'chore(admin)'
    groups:
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
      admin-dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
      admin-dependencies:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/apps/mobile'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'mobile'
    commit-message:
      prefix: 'chore(mobile)'
      prefix-development: 'chore(mobile)'
    groups:
      mobile-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      mobile-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
    groups:
      actions:
        patterns:
          - '*'
