version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'root'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    groups:
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'backend'
    commit-message:
      prefix: 'chore(backend)'
      prefix-development: 'chore(backend)'
      include: 'scope'
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
          - 'nest-*'
      testing:
        dependency-type: 'development'
        patterns:
          - 'jest*'
          - '@types/jest'
          - 'supertest'
          - '@types/supertest'
      backend-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
        exclude-patterns:
          - 'jest*'
          - '@types/jest'
          - 'supertest'
          - '@types/supertest'
      backend-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
        exclude-patterns:
          - '@prisma/*'
          - 'prisma'
    ignore:
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major']
      - dependency-name: 'prisma'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/packages/apps/admin'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'admin'
    commit-message:
      prefix: 'chore(admin)'
      prefix-development: 'chore(admin)'
      include: 'scope'
    groups:
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
      admin-testing:
        dependency-type: 'development'
        patterns:
          - '@playwright/*'
          - 'playwright'
          - 'cypress'
          - 'vitest'
          - '@vitest/*'
          - '@storybook/*'
          - 'storybook'
      admin-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
        exclude-patterns:
          - '@playwright/*'
          - 'playwright'
          - 'cypress'
          - 'vitest'
          - '@vitest/*'
          - '@storybook/*'
          - 'storybook'
      admin-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
        exclude-patterns:
          - 'react'
          - 'react-dom'
          - 'next'
    ignore:
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/packages/apps/mobile'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'mobile'
    commit-message:
      prefix: 'chore(mobile)'
      prefix-development: 'chore(mobile)'
      include: 'scope'
    groups:
      expo:
        patterns:
          - 'expo'
          - 'expo-*'
          - '@expo/*'
      react-native:
        patterns:
          - 'react-native'
          - 'react-native-*'
          - '@react-native*'
          - '@react-navigation/*'
      mobile-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      mobile-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
        exclude-patterns:
          - 'expo'
          - 'react-native'
    ignore:
      - dependency-name: 'expo'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
    groups:
      actions:
        patterns:
          - '*'
