version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'root'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
    groups:
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
    ignore:
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react-test-renderer'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/packages/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'backend'
    commit-message:
      prefix: 'chore(backend)'
      prefix-development: 'chore(backend)'
    groups:
      backend-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      backend-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/apps/admin'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'admin'
    commit-message:
      prefix: 'chore(admin)'
      prefix-development: 'chore(admin)'
    groups:
      admin-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      admin-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/apps/mobile'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'mobile'
    commit-message:
      prefix: 'chore(mobile)'
      prefix-development: 'chore(mobile)'
    groups:
      mobile-dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      mobile-patch-and-minor:
        update-types:
          - 'patch'
          - 'minor'
        patterns:
          - '*'
    ignore:
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'react-native-gesture-handler'
        versions: ['>2.24.0']
      - dependency-name: 'react-native-screens'
        versions: ['>4.11.1']
      - dependency-name: 'babel-preset-expo'
        versions: ['>13.0.0']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
    groups:
      actions:
        patterns:
          - '*'
