import { defineConfig } from 'cspell';

export default defineConfig({
  version: '0.2',
  language: 'en',
  words: [
    'autoincrement',
    'bunx',
    'commitlint',
    'cov',
    'env',
    'evenodd',
    'Dto',
    'healthcheck',
    'INITDB',
    'isready',
    'Kamil',
    'mau',
    'Myśliwiec',
    'nestframework',
    'lefthook',
    'logomark',
    'osx',
    'Pressable',
    'svh',
    'tsc',
    'turbopack',
    'typesync',
    'vitest',
  ],
  flagWords: [],
  ignorePaths: ['**/node_modules/**', '**/generated/**', '**/dist/**', 'packages/apps/backend/prisma/**'],
  maxNumberOfProblems: 0,
  minWordLength: 3,
});
