import { defineConfig } from 'cspell';

export default defineConfig({
  version: '0.2',
  language: 'en',
  words: [
    'Autodocs',
    'autoincrement',
    'awk',
    'basicauth',
    'bunx',
    'commitlint',
    'cov',
    'createmany',
    'createmanyandreturn',
    'customise',
    'env',
    'euo',
    'evenodd',
    'datetimepicker',
    'dbgenerated',
    'deletemany',
    'deletemanyandreturn',
    'Dto',
    'Dtos',
    'golevelup',
    'gorhom',
    'harddelete',
    'harddeletemany',
    'healthcheck',
    'INITDB',
    'isready',
    'iwashiro',
    'Kamil',
    'manyandreturn',
    'mau',
    'mts',
    'nent',
    'num',
    'Myśliwiec',
    'nestframework',
    'nonoctal',
    'lefthook',
    'logomark',
    'osx',
    'ondevice',
    'Pressable',
    'restoremany',
    'restoremanyandreturn',
    'rnstorybook',
    'setstate',
    'simctl',
    'svh',
    'Takuto',
    'takudev',
    'Takuya',
    'Tanaka',
    'Tarō',
    'transferrables',
    'tsc',
    'TSES',
    'turbopack',
    'ultrathink',
    'updatemany',
    'updatemanyandreturn',
    'vitest',
    'Wada',
    'xcrun',
  ],
  flagWords: [],
  ignorePaths: [
    '**/node_modules/**',
    '**/generated/**',
    '**/dist/**',
    'packages/apps/backend/prisma/**',
    '**/coverage/**',
    '**/playwright-report/index.html',
    '**/storybook-static/**',
    '.secretlintignore',
    'expo-env.d.ts',
  ],
  maxNumberOfProblems: 0,
  minWordLength: 3,
});
