name: Build and Start Mobile Project on Android
description: Build and start the mobile project on Android

runs:
  using: composite
  steps:
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: Nexus 6
        avd-name: test
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
          adb wait-for-device
          adb shell input keyevent 82
          bun run start:dev:android
