name: Setup Project Base
description: Checkout repository and setup bun with cache
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Bun with cache
      uses: ./.github/actions/setup-bun
