name: Start Mobile Server on Android
description: Start the mobile server on Android and wait for it to be ready

runs:
  using: composite
  steps:
    - name: Start Mobile Server on Android
      shell: bash
      run: |
        cd packages/apps/mobile
        emulator -avd test -no-window -no-audio -no-boot-anim &
        bun run start:dev:android & sleep 15
        bun run test
