name: Start Mobile Server on Android
description: Start the mobile server on Android and wait for it to be ready

runs:
  using: composite
  steps:
    - name: Start Mobile Server on Android
      shell: bash
      run: |
        cd packages/apps/mobile
        bun run start:dev:android &

        echo "Waiting for Mobile server to start..."

        timeout 60 bash -c '
          while true; do
            curl --silent --fail http://localhost:8081 >/dev/null 2>&1 && echo "✅ Mobile server is up!" && exit 0
            echo -n "."
            sleep 1
          done
        '

        if [ $? -ne 0 ]; then
          echo ""
          echo "❌ Mobile server failed to start within 60 seconds"
          exit 1
        fi
