name: 'Setup Bun with Cache'
description: 'Set up Node.js and Bun runtime with dependency caching for monorepo'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .tool-versions

    - name: Cache Bun Dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.bun/install/cache
          **/node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Notify Cache Hit
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "✅ Bun dependencies restored from cache."

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo " Installing dependencies with Bun..."
        bun install --frozen-lockfile
        echo "✅ Dependencies installed successfully"

    - name: Setup Env Variables
      shell: bash
      run: |
        echo "Setting up environment variables..."
        make setup-env
        echo "Environment variables set successfully."
