name: Setup Backend Project
description: Setup the backend project

inputs:
  need_db:
    description: 'Whether to set up the database'
    required: false
    default: 'true'
  skip_migrations:
    description: 'Whether to skip database migrations'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Backend Project
      shell: bash
      run: |
        make setup-env
        cd packages/apps/backend
        make setup NEED_DB=${{ inputs.need_db }} SKIP_MIGRATIONS=${{ inputs.skip_migrations }}
