name: Setup Backend Project
description: Setup the backend project
runs:
  using: composite
  steps:
    - name: Setup Backend Project
      shell: bash
      run: |
        cd packages/apps/backend
        make setup IS_CI=true
