name: CI/Static

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Bun with cache
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

  check-format:
    name: Check Format
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run Format Check
        run: bun run format:check

  check-shell-lint:
    name: Check Shell Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run Shell Lint Check
        run: bun run cspell

  check-secret-lint:
    name: Check Secret Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run Secret Lint Check
        run: bun run lint:secret:check

  check-markdown-lint:
    name: Check Markdown Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run Markdown Lint Check
        run: bun run lint:markdown:check

  check-dotenv-lint:
    name: Check Dotenv Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review
          dotenv_linter_flags: --skip UnorderedKey

  check-es-lint:
    name: Check ESLint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run ESLint Check
        run: bun run lint:es:check

  check-type:
    name: Check Type
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Setup Backend Project
        uses: ./.github/actions/setup-backend

      - name: Run Type Check
        run: bun run type:check

  # Additional jobs will be added in Phase 2:
  # - test
