name: CI / Static

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Base Project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

  check-format:
    name: Check Format
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Run Format Check
        run: bun run format:check

  check-shell-lint:
    name: Check Shell Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Run Shell Lint Check
        run: bun run cspell

  check-secret-lint:
    name: Check Secret Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Run Secret Lint Check
        run: bun run lint:secret:check

  check-markdown-lint:
    name: Check Markdown Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Run Markdown Lint Check
        run: bun run lint:markdown:check

  check-dotenv-lint:
    name: Check Dotenv Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review
          dotenv_linter_flags: --skip UnorderedKey

  check-es-lint:
    name: Check ESLint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Run ESLint Check
        run: bun run lint:es:check

  check-type:
    name: Check Type
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Setup Backend Project
        uses: ./.github/actions/setup-backend
        with:
          skip_migrations: 'true'
          need_db: 'false'

      - name: Run Type Check
        run: bun run type:check

  check-schema:
    name: Check Schema
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Setup Backend Project
        uses: ./.github/actions/setup-backend

      - name: Run Schema Check
        run: |
          cd packages/apps/backend
          bun run prisma:validate

      - name: Start Backend Server
        uses: ./.github/actions/start-backend

      - name: Generate Admin API Types
        run: |
          cd packages/apps/admin
          bun run gen:api-types

      - name: Generate Mobile API Types
        run: |
          cd packages/apps/mobile
          bun run gen:api-types

      - name: Check Diff
        run: |
          if ! git diff --quiet -- packages/apps/mobile/generated/types/api.d.ts packages/apps/admin/generated/types/api.d.ts; then
            echo "::error::Changes detected in API types. Please run 'bun run gen:api-types' to update them."
            exit 1
          fi
