name: CI / Test

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-admin:
    name: Apps / Test Admin
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project
        with:
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_team: ${{ secrets.TURBO_TEAM }}

      - name: Setup Backend Project
        uses: ./.github/actions/setup-backend

      - name: Start Backend Server
        uses: ./.github/actions/start-backend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Setup Admin Project
        uses: ./.github/actions/setup-admin

      - name: Start Admin Server
        uses: ./.github/actions/start-admin

      - name: Run Admin Tests
        run: |
          cd packages/apps/admin
          bun run test

      - name: Run Admin Tests (Coverage)
        run: |
          cd packages/apps/admin
          bun run test:cov

  test-backend:
    name: Apps / Test Backend
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project
        with:
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_team: ${{ secrets.TURBO_TEAM }}

      - name: Setup Backend Project
        uses: ./.github/actions/setup-backend

      - name: Start Backend Server
        uses: ./.github/actions/start-backend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Run Backend Tests
        run: |
          cd packages/apps/backend
          bun run test

      - name: Run Backend Tests (Coverage)
        run: |
          cd packages/apps/backend
          bun run test:cov

  test-mobile:
    name: Apps / Test Mobile
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project
        with:
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_team: ${{ secrets.TURBO_TEAM }}

      - name: Setup Mobile Project
        uses: ./.github/actions/setup-mobile

      - name: Run Mobile Unit Tests
        run: |
          cd packages/apps/mobile
          bun run test:unit

      - name: Run Mobile Tests (Coverage)
        run: |
          cd packages/apps/mobile
          bun run test:unit:cov

  eslint-plugin:
    name: Libs / Test ESLint Plugins
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project
        with:
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          turbo_team: ${{ secrets.TURBO_TEAM }}

      - name: Run ESLint Plugins Tests
        run: |
          cd packages/libs/eslint-plugins
          bun run test

      - name: Run ESLint Plugins Tests (Coverage)
        run: |
          cd packages/libs/eslint-plugins
          bun run test:cov
