name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup and Cache Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

  check-format:
    name: Check Format
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

      - name: Run format check
        run: bun run format:check

  check-shell-lint:
    name: Check Shell Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run shell lint check
        run: bun run cspell

  check-secret-lint:
    name: Check Secret Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run secret lint check
        run: bun run lint:secret:check

  check-markdown-lint:
    name: Check Markdown Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run markdown lint check
        run: bun run lint:markdown:check

  check-dotenv-lint:
    name: Check Dotenv Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review
          dotenv_linter_flags: --skip UnorderedKey

  check-es-lint:
    name: Check ESLint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

      - name: Run ESLint check
        run: bun run lint:es:check

  check-type:
    name: Check Type
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

      - name: Setup backend
        run: |
          echo "Setting up backend..."
          make setup-env
          cd packages/apps/backend
          make setup IS_CI=true SKIP_MIGRATIONS=true

      - name: Run type check
        run: bun run type:check

  # Additional jobs will be added in Phase 2:
  # - test
