name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup and Cache Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

  format-check:
    name: Format Check
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

      - name: Run format check
        run: bun run format:check

  cspell:
    name: Spell Check
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run spell check
        run: bun run cspell

  secretlint-check:
    name: Secret Detection
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run secret detection
        run: bun run secretlint:check

  markdown-check:
    name: Markdown Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Run markdown lint
        run: bun run markdown:check

  dotenv-check:
    name: Dotenv Lint
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review # Default is github-pr-check
          dotenv_linter_flags: --skip UnorderedKey

  lint-check:
    name: Lint Check
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun with cache
        uses: ./.github/actions/setup-bun

      - name: Build ESLint packages
        uses: ./.github/actions/build-eslint-packages

      - name: Run lint check
        run: bun run lint:check

  # Additional jobs will be added in Phase 2:
  # - lint-check
  # - type-check
  # - test
