name: Renovate

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *' # At 09:00 every day (JST)
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Base Project
        uses: ./.github/actions/setup-base-project

      - name: Self-Hosted Renovate
        uses: renovatebot/github-action@7876d7a812254599d262d62b6b2c2706018258a2 # v43.0.10
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
